# Generated by Django 4.2 on 2023-04-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articledata',
            old_name='name',
            new_name='title',
        ),
    ]
