# Generated by Django 4.2 on 2023-04-10 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GameData', '0004_articledata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledata',
            name='comments_amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='articledata',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='articledata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
