# Generated by Django 4.2 on 2023-04-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameData', '0008_rename_user_id_articledata_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videogame',
            options={'ordering': ['title']},
        ),
    ]
